### ISSUE TITLE
Is this still active?

### ISSUE THREAD

**Issue by filmaj** [adobe/datum#1]
Hello @anshulverma,

I'm Fil from Adobe's Open Source Office. Is this project still maintained? It's been a couple of years since the last commit. Wondering if there is someone still around to manage the project? Do we expect community involvement/contributions?

If so, can I send some pull requests to update the documentation? We need, at a minimum, contribution guidelines calling out the need to sign [Adobe's CLA](http://opensource.adobe.com/cla.html).

If no, can I archive the project, or remove it altogether?

I know you no longer work at Adobe, so thanks for any info if you can provide it!

Cheers,
Fil

**Comment by anshulverma** [comment]
Hi @filmaj,

I am the only maintainer for datum. I don't think there are anybody else involved or contributing to it. 

One of the main reason this is not in use is because I could not publish it before leaving Adobe. Now, I don't have the privilege to do so because this project needs to be published under `com.adobe.datum` which is a restricted repo in maven/bintray. Most probably someone in Adobe has access to do so.

I don't mind being the POC for this repo if its possible for me to do so by signing the CLA. Feel free to send the PR to update the project as per the requirements of Adobe's open source.

Thanks.

**Comment by filmaj** [comment]
@anshulverma thanks a lot for your response.

Do you recall which team it was you were on when you worked on this project? I can reach out to them to see if they are still using this project at all, and if they can become stewards of it.

I don't personally have a problem with you being the point of contact but at the same time I could see Adobe wanting to have an employee be the point of contact as well 😄 

In the mean time I will send documentation PRs.

Cheers and thanks for any info.

**Comment by anshulverma** [comment]
@filmaj I sent you an email that contains information you requested above.

**Comment by filmaj** [comment]
Thank you very much!
